name: Create EKS Cluster on AWS

on:
  workflow_dispatch:
    inputs:
      cluster_name:
        description: 'Name of the EKS cluster'
        required: true
        default: 'K8S-Blue-Green'
      region:
        description: 'AWS region'
        required: true
        default: 'us-east-1'

jobs:
  create-cluster:
    name: Create EKS Cluster
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ github.event.inputs.region }}
      CLUSTER_NAME: ${{ github.event.inputs.cluster_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS Cluster
        run: |
          eksctl create cluster \
            --name $CLUSTER_NAME \
            --region $AWS_REGION \
            --nodegroup-name standard-workers \
            --node-type t3.medium \
            --nodes 2 \
            --nodes-min 1 \
            --nodes-max 3 \
            --managed


