name: Create EKS Cluster on AWS

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: 
aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ 
secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ 
secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location 
"https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname 
-s)_amd64.tar.gz" -o eksctl.tar.gz
          tar -xzf eksctl.tar.gz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Make script executable
        run: chmod +x eksctl/create_cluster.sh

      - name: Execute script
        run: ./eksctl/create_cluster.sh


